# Generated by Django 4.1.3 on 2022-11-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
