# Generated by Django 4.1.3 on 2022-11-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('processing', 'Processing')], default='processing', max_length=50),
        ),
    ]
