# Generated by Django 4.1.3 on 2022-11-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Processing...', 'Processing')], default='Processing...', max_length=50),
        ),
    ]
